### ISSUE TITLE
Add feature to ignore one-line comments so that they do not throw exception on query execution

### ISSUE THREAD

**Issue by ask9** [simoc/csvjdbc#133]
Now when execute this query, it gives exception:
```
--some comment about the query
select * from some_table
```

![img1](https://github.com/user-attachments/assets/1b82789d-132b-49b6-994c-862a968c5d60)

**Comment by simoc** [comment]
You can use `--` for a single line comment, or C-style `/* ... */` comments in SQL statements in CsvJdbc.

However, A space is required after `--` so that expression `i--1` (which is more clearly written as `i - -1`) is not interpreted as a comment.

Use:

    -- some comment about the query
    select * from some_table

I will update the documentation to make this clear.

**Comment by ask9** [comment]
Please also don't forget to explain briefly in docs the meaning of the expression` i--1`
Actually, it is not very convenient solution for a user, but if there is no other way, well, okay...

**Comment by simoc** [comment]
This problem is fixed in Csvjdbc version 1.0.44.

Download it from https://sourceforge.net/projects/csvjdbc/files/ or from https://central.sonatype.com/
